[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "cosmo"
version = "0.2.0"
description = "Transient thermal CAD-CAE casing prototype"
dependencies = [
    "cadquery",
    "gmsh",
    "numpy",
    "matplotlib"
]

[tool.setuptools]
packages = ["cosmo", "cosmo.core", "cosmo.optimization"]
