import os
import subprocess
import json

def setup_and_run_calculix(inp_file, layers, od_mm, ccx_path="ccx\\calculix_2.22_4win\\ccx_static.exe", bht=150.0, time_seconds=14400):
    """
    Appends material properties and step definitions to the Gmsh .inp file,
    then runs CalculiX.
    
    Args:
        inp_file: The path to the gmsh generated .inp file.
        layers: List of layer dictionaries.
        od_mm: Outer diameter of the casing.
        ccx_path: Path to the ccx executable.
        bht: Bottom hole temperature (ambient).
        time_seconds: Simulation duration.
    """
    
    # Read material library
    with open("material_library.json", "r") as f:
        mat_lib = json.load(f)
        
    # Prepare appended content
    append_str = "\n** --- CALCULIX SETUP --- **\n"
    
    # 1. Materials & Solid Sections
    for i, layer in enumerate(layers):
        mat_name = layer['material']
        if mat_name not in mat_lib:
            raise ValueError(f"Material {mat_name} not found in library.")
            
        props = mat_lib[mat_name]
        
        append_str += f"*MATERIAL, NAME={mat_name}\n"
        append_str += f"*DENSITY\n{props['density']}\n"
        append_str += f"*CONDUCTIVITY\n{props['conductivity']}\n"
        append_str += f"*SPECIFIC HEAT\n{props['specific_heat']}\n"
        
        # Elsets are generated by gmsh based on the physical group name
        # We named them Layer_0, Layer_1, etc.
        elset_name = layer.get('name', f'Layer_{i}')
        append_str += f"*SOLID SECTION, ELSET={elset_name}, MATERIAL={mat_name}\n"

    # 2. Initial Conditions and OuterBoundary
    max_node = 0
    outer_nodes = []
    outer_r = od_mm / 2.0
    tol = 0.5
    
    with open(inp_file, "r") as f:
        in_node = False
        for line in f:
            if line.startswith("*NODE") or line.startswith("*Node"):
                in_node = True
                continue
            if in_node and line.startswith("*"):
                in_node = False
                continue
            if in_node:
                try:
                    parts = line.split(",")
                    nid = int(parts[0])
                    x, y = float(parts[1]), float(parts[2])
                    if nid > max_node:
                        max_node = nid
                    r = (x**2 + y**2)**0.5
                    if abs(r - outer_r) < tol:
                        outer_nodes.append(nid)
                except:
                    pass
                    
    append_str += f"*NSET, NSET=NALL, GENERATE\n1, {max_node}, 1\n"
    append_str += f"*INITIAL CONDITIONS, TYPE=TEMPERATURE\nNALL, 25.0\n"
    
    # Add OuterBoundary NSET
    if outer_nodes:
        append_str += f"*NSET, NSET=OuterBoundary\n"
        # Write nodes in chunks of 10 per line
        for i in range(0, len(outer_nodes), 10):
            chunk = outer_nodes[i:i+10]
            append_str += ", ".join(map(str, chunk)) + "\n"
    else:
        print("WARNING: Could not find nodes on the outer boundary!")

    # 3. Step Definition
    # Time step parameters: Initial time step size, total time, min time step, max time step
    dt_init = min(60.0, time_seconds/10.0)
    append_str += f"*STEP, INC=1000\n"
    append_str += f"*HEAT TRANSFER\n"
    append_str += f"{dt_init}, {time_seconds}, 1e-5, {dt_init*10}\n"
    
    # 4. Boundary Conditions
    # Apply BHT to OuterBoundary
    append_str += f"*BOUNDARY\nOuterBoundary, 11, 11, {bht}\n"
    
    # 5. Output
    append_str += f"*NODE FILE\nNT\n" # Export nodal temperatures
    append_str += f"*END STEP\n"

    # Append to the file
    with open(inp_file, "a") as f:
        f.write(append_str)
        
    print("Inp file modified with CalculiX properties.")
    
    # Run CalculiX
    # CalculiX takes the input file name WITHOUT the .inp extension
    job_name = os.path.splitext(os.path.basename(inp_file))[0]
    
    print(f"Running CalculiX job: {job_name} using {ccx_path}")
    
    # To run without hanging, we can use subprocess
    env = os.environ.copy()
    env["OMP_NUM_THREADS"] = "4" # Use 4 threads
    
    try:
        # ccx is in the ccx/ dir
        process = subprocess.run([ccx_path, "-i", job_name], 
                                 cwd=os.path.dirname(os.path.abspath(inp_file)),
                                 capture_output=True, text=True, check=True)
        print("CalculiX finished successfully.")
        return True
    except subprocess.CalledProcessError as e:
        print("CalculiX failed!")
        print(e.stdout)
        print(e.stderr)
        return False

if __name__ == "__main__":
    pass
