import os
import subprocess
import json

def setup_and_run_calculix(
    inp_file,
    layers,
    od_mm,
    ccx_path=None,
    bht=150.0,
    time_seconds=14400,
    internal_power_w=0.0,
    include_end_boundaries=False,
    power_z_bounds=None,
):
    """
    Appends material properties and step definitions to the Gmsh .inp file,
    then runs CalculiX.
    
    Args:
        inp_file: The path to the gmsh generated .inp file.
        layers: List of layer dictionaries.
        od_mm: Outer diameter of the casing.
        ccx_path: Path to the ccx executable.
        bht: Bottom hole temperature (ambient).
        time_seconds: Simulation duration.
    """
    if ccx_path is None:
        from pathlib import Path
        ccx_path = str((Path(__file__).parent.parent / "ccx" / "calculix_2.22_4win" / "ccx_static.exe").resolve())
    
    # Read material library
    from pathlib import Path
    mat_lib_path = Path(__file__).parent.parent / "material_library.json"
    with open(mat_lib_path, "r") as f:
        mat_lib = json.load(f)
        
    # Prepare appended content
    append_str = "\n** --- CALCULIX SETUP --- **\n"
    
    # 1. Materials & Solid Sections
    defined_materials = set()
    for i, layer in enumerate(layers):
        mat_name = layer['material']
        if mat_name not in mat_lib:
            raise ValueError(f"Material {mat_name} not found in library.")
            
        props = mat_lib[mat_name]
        
        # Convert SI properties to the consistent mm-N-s-C system.
        # Density: kg/m^3 -> N.s^2/mm^4 (multiply by 1e-12)
        density_mm = props['density'] * 1e-12
        # Conductivity: W/(m.K) and mW/(mm.K) are numerically identical.
        cond_mm = props['conductivity']
        # Specific Heat: J/(kg.K) -> (mJ/tonne.K) / (mm^2/s^2.K) (multiply by 1e6)
        cp_mm = props['specific_heat'] * 1e6
        
        if mat_name not in defined_materials:
            append_str += f"*MATERIAL, NAME={mat_name}\n"
            append_str += f"*DENSITY\n{density_mm:.6E}\n"
            append_str += f"*CONDUCTIVITY\n{cond_mm:.6E}\n"
            append_str += f"*SPECIFIC HEAT\n{cp_mm:.6E}\n"
            defined_materials.add(mat_name)
        
        # Elsets are generated by gmsh based on the physical group name
        # We named them Layer_0, Layer_1, etc.
        elset_name = layer.get('name', f'Layer_{i}')
        append_str += f"*SOLID SECTION, ELSET={elset_name}, MATERIAL={mat_name}\n"

    # 2. Initial Conditions and OuterBoundary
    outer_r = od_mm / 2.0
    tol = 0.5
    
    nodes = {}
    with open(inp_file, "r") as f:
        in_node = False
        for line in f:
            if line.startswith("*NODE") or line.startswith("*Node"):
                in_node = True
                continue
            if in_node and line.startswith("*"):
                in_node = False
                continue
            if in_node:
                try:
                    parts = line.split(",")
                    nid = int(parts[0])
                    x, y, z = float(parts[1]), float(parts[2]), float(parts[3])
                except (IndexError, ValueError) as exc:
                    raise ValueError(f"Malformed node line in {inp_file}: {line.rstrip()}") from exc
                nodes[nid] = (x, y, z)

    if not nodes:
        raise ValueError(f"No nodes found in {inp_file}")
    z_min = min(value[2] for value in nodes.values())
    z_max = max(value[2] for value in nodes.values())
    outer_nodes = [
        nid
        for nid, (x, y, z) in nodes.items()
        if abs((x**2 + y**2) ** 0.5 - outer_r) < tol
        or include_end_boundaries and (abs(z - z_min) < tol or abs(z - z_max) < tol)
    ]
    if not outer_nodes:
        raise ValueError(f"No nodes found on outer radius {outer_r} mm in {inp_file}")
                    
    # Enumerate all discovered nodes explicitly to handle non-contiguous IDs
    all_node_ids = sorted(nodes)
    append_str += f"*NSET, NSET=NALL\n"
    for i in range(0, len(all_node_ids), 10):
        chunk = all_node_ids[i:i+10]
        append_str += ", ".join(map(str, chunk)) + "\n"
        
    append_str += f"*INITIAL CONDITIONS, TYPE=TEMPERATURE\nNALL, 25.0\n"
    
    # Add OuterBoundary NSET
    append_str += f"*NSET, NSET=OuterBoundary\n"
    for i in range(0, len(outer_nodes), 10):
        chunk = outer_nodes[i:i+10]
        append_str += ", ".join(map(str, chunk)) + "\n"

    # 3. Step Definition
    # Time step parameters: Initial time step size, total time, min time step, max time step
    dt_init = min(60.0, time_seconds/10.0)
    append_str += f"*STEP, INC=1000\n"
    append_str += f"*HEAT TRANSFER\n"
    append_str += f"{dt_init}, {time_seconds}, 1e-5, {dt_init*10}\n"
    
    # 4. Boundary Conditions
    # Apply BHT to OuterBoundary
    append_str += f"*BOUNDARY\nOuterBoundary, 11, 11, {bht}\n"
    if internal_power_w:
        inner_r = outer_r - sum(layer['thickness'] for layer in layers)
        inner_nodes = [
            nid for nid, (x, y, z) in nodes.items()
            if abs((x**2 + y**2) ** 0.5 - inner_r) < tol
            and (power_z_bounds is None or power_z_bounds[0] <= z <= power_z_bounds[1])
        ]
        if not inner_nodes:
            raise ValueError(f"No nodes found on inner radius {inner_r} mm in {inp_file}")
        nodal_power = internal_power_w * 1000.0 / len(inner_nodes)
        append_str += "*CFLUX\n"
        for nid in inner_nodes:
            append_str += f"{nid}, 11, {nodal_power:.9E}\n"
    
    # 5. Output
    append_str += f"*NODE FILE\nNT\n" # Export nodal temperatures
    append_str += f"*END STEP\n"

    # Append to the file
    with open(inp_file, "a") as f:
        f.write(append_str)
        
    print("Inp file modified with CalculiX properties.")
    
    # Run CalculiX
    # CalculiX takes the input file name WITHOUT the .inp extension
    job_name = os.path.splitext(os.path.basename(inp_file))[0]
    job_dir = os.path.dirname(os.path.abspath(inp_file))
    for suffix in (".frd", ".dat", ".sta", ".cvg", ".12d"):
        stale = os.path.join(job_dir, job_name + suffix)
        if os.path.exists(stale):
            os.remove(stale)
    
    print(f"Running CalculiX job: {job_name} using {ccx_path}")
    
    # To run without hanging, we can use subprocess
    env = os.environ.copy()
    env["OMP_NUM_THREADS"] = "4" # Use 4 threads
    
    try:
        # ccx is in the ccx/ dir
        process = subprocess.run([ccx_path, "-i", job_name], 
                                 cwd=job_dir,
                                 capture_output=True, text=True, check=True, env=env)
        output = f"{process.stdout or ''}{process.stderr or ''}"
        with open(os.path.join(job_dir, job_name + ".stdout.txt"), "w", encoding="utf-8") as log:
            log.write(output)
        if "*ERROR" in output.upper() or "FATAL" in output.upper():
            print("CalculiX reported a fatal input/solver error.")
            return False
        print("CalculiX finished successfully.")
        return True
    except subprocess.CalledProcessError as e:
        print("CalculiX failed!")
        print(e.stdout)
        print(e.stderr)
        return False
